//! Trace generation for the Blake round component.
//!
//! Row generation is embarrassingly parallel: every vec-row writes a disjoint
//! slot of each column. The trace columns are therefore split into contiguous
//! row chunks, each generated independently (one xor-multiplicity accumulator
//! per chunk, merged at the end).

use std::simd::u32x16;

use itertools::{chain, Itertools};
use num_traits::One;
#[cfg(feature = "parallel")]
use rayon::prelude::*;
use stwo::core::fields::m31::BaseField;
use stwo::core::fields::qm31::SecureField;
use stwo::core::poly::circle::CanonicCoset;
use stwo::core::ColumnVec;
use stwo::prover::backend::simd::column::BaseColumn;
use stwo::prover::backend::simd::m31::{PackedBaseField, LOG_N_LANES};
use stwo::prover::backend::simd::qm31::PackedSecureField;
use stwo::prover::backend::simd::SimdBackend;
use stwo::prover::backend::{Col, Column};
use stwo::prover::poly::circle::CircleEvaluation;
use stwo::prover::poly::BitReversedOrder;
use stwo_constraint_framework::{LogupTraceGenerator, Relation, ORIGINAL_TRACE_IDX};
use tracing::{span, Level};

use super::{BlakeXorElements, RoundElements};
use crate::blake::round::blake_round_info;
use crate::blake::{to_felts, XorAccums, N_ROUND_INPUT_FELTS, STATE_SIZE};

/// Widths of the xor lookups appended by a single `g` call, in append order:
/// `xor_rotr16_u32` appends four width-8 lookups, then the three `xor_rotr_u32`
/// calls with r = 12, 8, 7 each append widths [r, r, 16 - r, 16 - r].
const G_XOR_WIDTHS: [u32; 16] = [8, 8, 8, 8, 12, 12, 4, 4, 8, 8, 8, 8, 7, 7, 9, 9];
/// Number of `g` calls per row (one per mixing step of the round).
const N_G_PER_ROW: usize = 8;

pub struct BlakeRoundLookupData {
    /// A vector of (w, [a_col, b_col, c_col]) for each xor lookup.
    /// w is the xor width. c_col is the xor col of a_col and b_col.
    xor_lookups: Vec<(u32, [BaseColumn; 3])>,
    /// A column of round lookup values (v_in, v_out, m).
    round_lookup: [BaseColumn; N_ROUND_INPUT_FELTS],
}

struct TraceGenerator {
    trace: Vec<BaseColumn>,
    xor_lookups: Vec<(u32, [BaseColumn; 3])>,
    round_lookup: [BaseColumn; N_ROUND_INPUT_FELTS],
}
impl TraceGenerator {
    fn new(log_size: u32) -> Self {
        assert!(log_size >= LOG_N_LANES);
        let trace = (0..blake_round_info().mask_offsets[ORIGINAL_TRACE_IDX].len())
            .map(|_| unsafe { Col::<SimdBackend, BaseField>::uninitialized(1 << log_size) })
            .collect_vec();
        let xor_lookups = (0..N_G_PER_ROW)
            .flat_map(|_| G_XOR_WIDTHS)
            .map(|w| {
                (
                    w,
                    std::array::from_fn(|_| unsafe { BaseColumn::uninitialized(1 << log_size) }),
                )
            })
            .collect_vec();
        Self {
            trace,
            xor_lookups,
            round_lookup: std::array::from_fn(|_| unsafe {
                BaseColumn::uninitialized(1 << log_size)
            }),
        }
    }
}

/// Mutable view over a contiguous range of vec-rows of all generated columns.
/// Each chunk is generated by an independent task.
struct TraceChunkView<'a> {
    trace: Vec<&'a mut [PackedBaseField]>,
    xor_lookups: Vec<(u32, [&'a mut [PackedBaseField]; 3])>,
    round_lookup: Vec<&'a mut [PackedBaseField]>,
}

/// Trace generator for the constraints defined at [`super::constraints::BlakeRoundEval`],
/// writing a single vec-row within a [`TraceChunkView`].
struct TraceGeneratorRow<'a, 'b> {
    view: &'b mut TraceChunkView<'a>,
    col_index: usize,
    local_row: usize,
    xor_lookups_index: usize,
}
impl TraceGeneratorRow<'_, '_> {
    fn append_felt(&mut self, val: u32x16) {
        self.view.trace[self.col_index][self.local_row] =
            unsafe { PackedBaseField::from_simd_unchecked(val) };
        self.col_index += 1;
    }

    fn append_u32(&mut self, val: u32x16) {
        self.append_felt(val & u32x16::splat(0xffff));
        self.append_felt(val >> 16);
    }

    fn generate(&mut self, mut v: [u32x16; 16], m: [u32x16; 16]) {
        let input_v = v;
        v.iter().for_each(|s| {
            self.append_u32(*s);
        });
        m.iter().for_each(|s| {
            self.append_u32(*s);
        });

        self.g(v.get_disjoint_mut([0, 4, 8, 12]).unwrap(), m[0], m[1]);
        self.g(v.get_disjoint_mut([1, 5, 9, 13]).unwrap(), m[2], m[3]);
        self.g(v.get_disjoint_mut([2, 6, 10, 14]).unwrap(), m[4], m[5]);
        self.g(v.get_disjoint_mut([3, 7, 11, 15]).unwrap(), m[6], m[7]);
        self.g(v.get_disjoint_mut([0, 5, 10, 15]).unwrap(), m[8], m[9]);
        self.g(v.get_disjoint_mut([1, 6, 11, 12]).unwrap(), m[10], m[11]);
        self.g(v.get_disjoint_mut([2, 7, 8, 13]).unwrap(), m[12], m[13]);
        self.g(v.get_disjoint_mut([3, 4, 9, 14]).unwrap(), m[14], m[15]);

        let local_row = self.local_row;
        chain![input_v.iter(), v.iter(), m.iter()]
            .flat_map(to_felts)
            .enumerate()
            .for_each(|(i, felt)| self.view.round_lookup[i][local_row] = felt);
    }

    fn g(&mut self, v: [&mut u32x16; 4], m0: u32x16, m1: u32x16) {
        let [a, b, c, d] = v;

        *a = self.add3_u32s(*a, *b, m0);
        *d = self.xor_rotr16_u32(*a, *d);
        *c = self.add2_u32s(*c, *d);
        *b = self.xor_rotr_u32(*b, *c, 12);
        *a = self.add3_u32s(*a, *b, m1);
        *d = self.xor_rotr_u32(*a, *d, 8);
        *c = self.add2_u32s(*c, *d);
        *b = self.xor_rotr_u32(*b, *c, 7);
    }

    /// Adds two u32s, returning the sum.
    fn add2_u32s(&mut self, a: u32x16, b: u32x16) -> u32x16 {
        let s = a + b;
        self.append_u32(s);
        s
    }

    /// Adds three u32s, returning the sum.
    fn add3_u32s(&mut self, a: u32x16, b: u32x16, c: u32x16) -> u32x16 {
        let s = a + b + c;
        self.append_u32(s);
        s
    }

    /// Splits a felt at r.
    fn split(&mut self, a: u32x16, r: u32) -> (u32x16, u32x16) {
        let h = a >> r;
        let l = a & u32x16::splat((1 << r) - 1);
        self.append_felt(h);
        (l, h)
    }

    /// Checks that a, b are in range, and computes their xor rotated right by `r` bits.
    fn xor_rotr_u32(&mut self, a: u32x16, b: u32x16, r: u32) -> u32x16 {
        let c = a ^ b;
        let cr = (c >> r) | (c << (32 - r));

        let (all, alh) = self.split(a & u32x16::splat(0xffff), r);
        let (ahl, ahh) = self.split(a >> 16, r);
        let (bll, blh) = self.split(b & u32x16::splat(0xffff), r);
        let (bhl, bhh) = self.split(b >> 16, r);

        self.xor(r, all, bll);
        self.xor(r, ahl, bhl);
        self.xor(16 - r, alh, blh);
        self.xor(16 - r, ahh, bhh);

        cr
    }

    /// Checks that a, b are in range, and computes their xor rotated right by 16 bits.
    fn xor_rotr16_u32(&mut self, a: u32x16, b: u32x16) -> u32x16 {
        let c = a ^ b;
        let cr = (c >> 16) | (c << 16);

        let (all, alh) = self.split(a & u32x16::splat(0xffff), 8);
        let (ahl, ahh) = self.split(a >> 16, 8);
        let (bll, blh) = self.split(b & u32x16::splat(0xffff), 8);
        let (bhl, bhh) = self.split(b >> 16, 8);

        self.xor(8, all, bll);
        self.xor(8, ahl, bhl);
        self.xor(8, alh, blh);
        self.xor(8, ahh, bhh);

        cr
    }

    /// Checks that a, b are in [0, 2^w) and computes their xor.
    /// a,b,a^b are assumed to fit in a single felt.
    fn xor(&mut self, w: u32, a: u32x16, b: u32x16) -> u32x16 {
        let c = a ^ b;
        self.append_felt(c);
        let (expected_w, cols) = &mut self.view.xor_lookups[self.xor_lookups_index];
        debug_assert_eq!(
            *expected_w, w,
            "xor lookup width schedule out of sync with G_XOR_WIDTHS"
        );
        cols[0][self.local_row] = unsafe { PackedBaseField::from_simd_unchecked(a) };
        cols[1][self.local_row] = unsafe { PackedBaseField::from_simd_unchecked(b) };
        cols[2][self.local_row] = unsafe { PackedBaseField::from_simd_unchecked(c) };
        self.xor_lookups_index += 1;
        c
    }
}

#[derive(Copy, Clone, Default)]
pub struct BlakeRoundInput {
    pub v: [u32x16; STATE_SIZE],
    pub m: [u32x16; STATE_SIZE],
}

/// Generates one chunk of rows, accumulating xor multiplicities into `xor_accum`.
fn generate_chunk(
    mut view: TraceChunkView<'_>,
    row_offset: usize,
    inputs: &[BlakeRoundInput],
    xor_accum: &mut XorAccums,
) {
    let n_rows = view.trace[0].len();
    for local_row in 0..n_rows {
        let vec_row = row_offset + local_row;
        let BlakeRoundInput { v, m } = inputs.get(vec_row).copied().unwrap_or_default();
        let mut row_gen = TraceGeneratorRow {
            view: &mut view,
            col_index: 0,
            local_row,
            xor_lookups_index: 0,
        };
        row_gen.generate(v, m);
        for (w, [a, b, _c]) in &view.xor_lookups {
            xor_accum.add_input(*w, a[local_row].into_simd(), b[local_row].into_simd());
        }
    }
}

pub fn generate_trace(
    log_size: u32,
    inputs: &[BlakeRoundInput],
    xor_accum: &mut XorAccums,
) -> (
    ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
    BlakeRoundLookupData,
) {
    let _span = span!(Level::INFO, "Round Generation").entered();
    let mut generator = TraceGenerator::new(log_size);
    let n_vec_rows: usize = 1 << (log_size - LOG_N_LANES);

    #[cfg(feature = "parallel")]
    let n_chunks = rayon::current_num_threads().clamp(1, n_vec_rows);
    #[cfg(not(feature = "parallel"))]
    let n_chunks = 1;
    let chunk_size = n_vec_rows.div_ceil(n_chunks);

    // Split every column into disjoint per-chunk row ranges.
    let mut trace_chunks = generator
        .trace
        .iter_mut()
        .map(|c| c.data.chunks_mut(chunk_size))
        .collect_vec();
    let mut xor_chunks = generator
        .xor_lookups
        .iter_mut()
        .map(|(w, cols)| (*w, cols.each_mut().map(|c| c.data.chunks_mut(chunk_size))))
        .collect_vec();
    let mut round_chunks = generator
        .round_lookup
        .iter_mut()
        .map(|c| c.data.chunks_mut(chunk_size))
        .collect_vec();

    let views = (0..n_vec_rows.div_ceil(chunk_size))
        .map(|_| TraceChunkView {
            trace: trace_chunks
                .iter_mut()
                .map(|it| it.next().unwrap())
                .collect(),
            xor_lookups: xor_chunks
                .iter_mut()
                .map(|(w, its)| (*w, its.each_mut().map(|it| it.next().unwrap())))
                .collect(),
            round_lookup: round_chunks
                .iter_mut()
                .map(|it| it.next().unwrap())
                .collect(),
        })
        .collect_vec();

    #[cfg(feature = "parallel")]
    {
        // Tree-reduce the per-chunk accumulators so the (large) multiplicity-table
        // merges also run in parallel instead of sequentially on one thread.
        let merged = views
            .into_par_iter()
            .enumerate()
            .map(|(chunk_idx, view)| {
                let mut acc = XorAccums::default();
                generate_chunk(view, chunk_idx * chunk_size, inputs, &mut acc);
                acc
            })
            .reduce_with(|mut a, b| {
                a.merge(b);
                a
            });
        if let Some(merged) = merged {
            xor_accum.merge(merged);
        }
    }
    #[cfg(not(feature = "parallel"))]
    for (chunk_idx, view) in views.into_iter().enumerate() {
        generate_chunk(view, chunk_idx * chunk_size, inputs, xor_accum);
    }

    let domain = CanonicCoset::new(log_size).circle_domain();
    (
        generator
            .trace
            .into_iter()
            .map(|eval| CircleEvaluation::new(domain, eval))
            .collect(),
        BlakeRoundLookupData {
            xor_lookups: generator.xor_lookups,
            round_lookup: generator.round_lookup,
        },
    )
}

pub fn generate_interaction_trace(
    log_size: u32,
    lookup_data: BlakeRoundLookupData,
    xor_lookup_elements: &BlakeXorElements,
    round_lookup_elements: &RoundElements,
) -> (
    ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
    SecureField,
) {
    let _span = span!(Level::INFO, "Generate round interaction trace").entered();
    let mut logup_gen = LogupTraceGenerator::new(log_size);
    let n_vec_rows: usize = 1 << (log_size - LOG_N_LANES);

    for [(w0, l0), (w1, l1)] in lookup_data.xor_lookups.as_chunks::<2>().0 {
        let frac_at_row = |vec_row: usize| {
            let p0: PackedSecureField =
                xor_lookup_elements.combine(*w0, &l0.each_ref().map(|l| l.data[vec_row]));
            let p1: PackedSecureField =
                xor_lookup_elements.combine(*w1, &l1.each_ref().map(|l| l.data[vec_row]));
            (p0 + p1, p0 * p1)
        };

        #[cfg(feature = "parallel")]
        logup_gen.col_from_par_iter((0..n_vec_rows).into_par_iter().map(frac_at_row));
        #[cfg(not(feature = "parallel"))]
        logup_gen.col_from_iter((0..n_vec_rows).map(frac_at_row));
    }

    let round_frac_at_row = |vec_row: usize| {
        let p = round_lookup_elements
            .combine(&lookup_data.round_lookup.each_ref().map(|l| l.data[vec_row]));
        (-PackedSecureField::one(), p)
    };
    #[cfg(feature = "parallel")]
    logup_gen.col_from_par_iter((0..n_vec_rows).into_par_iter().map(round_frac_at_row));
    #[cfg(not(feature = "parallel"))]
    logup_gen.col_from_iter((0..n_vec_rows).map(round_frac_at_row));

    logup_gen.finalize_last()
}
